modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Minor Convenience"
logoFile="minorconvenience.png"
authors="${mod_authors}"
clientSideOnly=true

description='''This mod is simply a collection of minor conveniences intended to be used on Hypixel Skyblock.
'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="CLIENT"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"